version: 2.1

description: "Provides functionality related to running Cypress.io tests"

executors:
  default:
    description:
      "Uses an image with Cypress CLI pre-installed" 
    parameters:
      tag:
        type: string
        default: "8"
    docker:
      - image: cypress/base:<< parameters.tag >>
  chrome:
    description:
      "Uses an image with all dependencies for Cypress included browsers 
      Chrome 67"
    parameters:
      tag:
        type: string
        default: "chrome67"
    docker:
      - image: cypress/browsers:<< parameters.tag >>
  basepack:
    description:
      Uses the basic buildpack-deps image, which has the
      prerequisites for installing Cypress' CLI.
    parameters:
      tag:
        type: string
        default: "bionic"
    docker:
      - image: buildpack-deps:<< parameters.tag >>

commands:
  install:
    steps:
      - run:
          name: "Install Cypress CLI, if necessary"
          command: |
            if [[ $(command -v npm) == "" ]]; then
              echo "NPM is required to install Cypress and not installed."
              return 1
            else 
              if [[ $(command -v $(npm bin)/cypress) == "" ]]; then
                cd 
                npm install cypress
              else
                echo "Cypress is already installed. No operation was performed."
              fi
            fi
jobs:
  install:
    parameters:
      dir:
        description:
          "The root directory of your source code tree. The default value is  
          the location of $CIRCLE_WORKING_DIRECTORY"
        type: string
        default: $CIRCLE_WORKING_DIRECTORY
    executor: default
    working_directory: << parameters.dir >>
    steps:
      - install
      - run: $(npm bin)/cypress run
  install_basepack:
    parameters:
      dir:
        description:
          "The root directory of your source code tree. The default value is  
          the location of $CIRCLE_WORKING_DIRECTORY"
        type: string
        default: $CIRCLE_WORKING_DIRECTORY
    executor: basepack
    working_directory: << parameters.dir >>
    steps:
      - install
      - run: $(npm bin)/cypress run
