version: 2.1

description: "Provides functionality related to running Cypress.io tests"

executors:
  default:
    description:
      "Uses an image with all dependencies for Cypress included browsers 
      Chrome 67"
    parameters:
      tag:
        type: string
        default: "chrome67"
    docker:
      - image: cypress/browsers:<< parameters.tag >>
  basepack:
    description:
      Uses the basic buildpack-deps image, which has the
      prerequisites for installing Cypress' CLI.
    parameters:
      tag:
        type: string
        default: "bionic"
    docker:
      - image: buildpack-deps:<< parameters.tag >>

commands:
  install:
    steps:
      - run:
          name: "Install Cypress CLI, if necessary"
          command: |
            if [[ $(command -v cypress) == "" ]]; then
              npm install cypress
            else
              echo "Cypress is already installed. No operation was performed."
            fi
jobs:
  install:
    executor: default
    steps:
      - install
      - checkout
      - cypress run
  install:
    executor: basepack
    steps:
      - install
      - checkout
      - cypress run
